import { DomainPrimitive, ValueObject } from '../base-classes/value-object.base';
import { ValueOf } from '../types/value-of.type';
declare const VALUE: {
    readonly BATTERY_TEMPERATURE: "battery_temperature";
    readonly BROKEN_CHARGING: "broken_charging";
    readonly BROKEN_CHARGING_WAIT: "broken_charging_wait";
    readonly BROKEN_GO_HOME: "broken_go_home";
    readonly BUMPER_STRUCT: "bumper_struct";
    readonly CHECK_NET_AVAILABLE: "check_net_available";
    readonly CLIFF_IR_STRUCT: "cliff_ir_struct";
    readonly DISHCLOTH_DIRTY: "dishcloth_dirty";
    readonly DOCK_CLIP_EXCEPTION: "dock_clip_exception";
    readonly DUSTBOX_NOT_EXIST: "dustbox_not_exist";
    readonly DUST_BOX_FULL: "dust_box_full";
    readonly ESCAPE_FAILED: "escape_failed";
    readonly FOLLOWE_IR_EXCEPTION: "followe_ir_exception";
    readonly GEOMAGETISM_STRUCT: "geomagetism_struct";
    readonly GIVE_BACK: "give_back";
    readonly GLOBAL_APPOINT_CLEAN: "global_appoint_clean";
    readonly GO_DOCK_FAILED: "go_dock_failed";
    readonly HANDPPEN_DUST_BOX_FULL: "handppen_dust_box_full";
    readonly HUICHENGHE_FULL: "huichenghe_full";
    readonly LIDAR_TIME_OUT: "lidar_time_out";
    readonly LOW_POWER_PLAN_DIS: "low_power_plan_dis";
    readonly LOW_START_BATTERY: "low_start_battery";
    readonly MOPPING_NOT_EXIST: "mopping_not_exist";
    readonly NONE: "none";
    readonly PUT_MACHINE_DOCK: "put_machine_dock";
    readonly RELOCALIZATION_FAILED: "relocalization_failed";
    readonly ROBOT_CHANGING_FINISH: "robot_changing_finish";
    readonly ROBOT_RELOCALITION_ING: "robot_relocalition_ing";
    readonly ROBOT_REPEAT_CLEANING: "robot_repeat_cleaning";
    readonly ROBOT_SELF_CHECKING: "robot_self_checking";
    readonly ROLL_BRUSH_STALL: "roll_brush_stall";
    readonly SIDE_BRUSH_STALL: "side_brush_stall";
    readonly SLOPE_START_FAILED: "slope_start_failed";
    readonly START_DOCK_FAILED: "start_dock_failed";
    readonly SYSTEM_UPGRADE: "system_upgrade";
    readonly WAIT_CHARGE_FINISH: "wait_charge_finish";
    readonly WATER_BOX_NOT_EXIST: "water_box_not_exist";
    readonly WATER_TRUNK_EMPTY: "water_trunk_empty";
    readonly WHEEL_UP: "wheel_up";
};
type Value = ValueOf<typeof VALUE>;
export declare class DeviceError extends ValueObject<Value> {
    get value(): Value;
    protected validate(props: DomainPrimitive<Value>): void;
    static VALUE: {
        readonly BATTERY_TEMPERATURE: "battery_temperature";
        readonly BROKEN_CHARGING: "broken_charging";
        readonly BROKEN_CHARGING_WAIT: "broken_charging_wait";
        readonly BROKEN_GO_HOME: "broken_go_home";
        readonly BUMPER_STRUCT: "bumper_struct";
        readonly CHECK_NET_AVAILABLE: "check_net_available";
        readonly CLIFF_IR_STRUCT: "cliff_ir_struct";
        readonly DISHCLOTH_DIRTY: "dishcloth_dirty";
        readonly DOCK_CLIP_EXCEPTION: "dock_clip_exception";
        readonly DUSTBOX_NOT_EXIST: "dustbox_not_exist";
        readonly DUST_BOX_FULL: "dust_box_full";
        readonly ESCAPE_FAILED: "escape_failed";
        readonly FOLLOWE_IR_EXCEPTION: "followe_ir_exception";
        readonly GEOMAGETISM_STRUCT: "geomagetism_struct";
        readonly GIVE_BACK: "give_back";
        readonly GLOBAL_APPOINT_CLEAN: "global_appoint_clean";
        readonly GO_DOCK_FAILED: "go_dock_failed";
        readonly HANDPPEN_DUST_BOX_FULL: "handppen_dust_box_full";
        readonly HUICHENGHE_FULL: "huichenghe_full";
        readonly LIDAR_TIME_OUT: "lidar_time_out";
        readonly LOW_POWER_PLAN_DIS: "low_power_plan_dis";
        readonly LOW_START_BATTERY: "low_start_battery";
        readonly MOPPING_NOT_EXIST: "mopping_not_exist";
        readonly NONE: "none";
        readonly PUT_MACHINE_DOCK: "put_machine_dock";
        readonly RELOCALIZATION_FAILED: "relocalization_failed";
        readonly ROBOT_CHANGING_FINISH: "robot_changing_finish";
        readonly ROBOT_RELOCALITION_ING: "robot_relocalition_ing";
        readonly ROBOT_REPEAT_CLEANING: "robot_repeat_cleaning";
        readonly ROBOT_SELF_CHECKING: "robot_self_checking";
        readonly ROLL_BRUSH_STALL: "roll_brush_stall";
        readonly SIDE_BRUSH_STALL: "side_brush_stall";
        readonly SLOPE_START_FAILED: "slope_start_failed";
        readonly START_DOCK_FAILED: "start_dock_failed";
        readonly SYSTEM_UPGRADE: "system_upgrade";
        readonly WAIT_CHARGE_FINISH: "wait_charge_finish";
        readonly WATER_BOX_NOT_EXIST: "water_box_not_exist";
        readonly WATER_TRUNK_EMPTY: "water_trunk_empty";
        readonly WHEEL_UP: "wheel_up";
    };
}
export {};
